version: 2
updates:
  - package-ecosystem: cargo
    directories:
      - "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 6

  # split from root directory schedule to avoid duplicate checks
  - package-ecosystem: cargo
    directories:
      - "/dev-bins"
      - "/ci/xtask"
      - "/programs/sbf"
    schedule:
      interval: daily
      time: "14:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 6

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 3
