[package]
name = "solana-svm-test-harness"
description = "Solana SVM test harness."
documentation = "https://docs.rs/solana-svm-test-harness"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = false

[[bin]]
name = "test_exec_instr"
path = "bin/test_exec_instr.rs"
required-features = ["fuzz"]

[features]
agave-unstable-api = []
dummy-for-ci-check = ["fuzz"]
fuzz = [
    "dep:clap",
    "dep:prost",
    "solana-svm-test-harness-fixture/fuzz",
    "solana-svm-test-harness-instr/fuzz",
]

[dependencies]
agave-logger = { workspace = true }
clap = { version = "4.5.2", features = ["derive"], optional = true }
prost = { workspace = true, optional = true }
solana-svm-test-harness-fixture = { workspace = true }
solana-svm-test-harness-instr = { workspace = true }

[lints]
workspace = true
