name: Benchmark
on:
  push:

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: rust benchmark
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pkg:
          - solana-runtime
          - solana-gossip
          - solana-poh
          - solana-sdk
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          source ci/rust-version.sh nightly
          sudo apt update
          sudo apt install protobuf-compiler -y

      - name: Run benchmark
        run: |
          source ci/rust-version.sh all
          cargo +$rust_nightly bench -p ${{matrix.pkg}} | tee output.txt

      # - name: Store benchmark result
      #   uses: benchmark-action/github-action-benchmark@v1
      #   with:
      #     name: ${{matrix.pkg}}
      #     tool: "cargo"
      #     output-file-path: output.txt
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     auto-push: true
